// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/auth-screen/Register.tsx": () => import("../components/mockups/auth-screen/Register.tsx"),
  "./components/mockups/auth-screen/Verify.tsx": () => import("../components/mockups/auth-screen/Verify.tsx")
};
