// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-screen/Home.tsx": () => import("../components/mockups/home-screen/Home.tsx"),
  "./components/mockups/welcome-screen/Welcome.tsx": () => import("../components/mockups/welcome-screen/Welcome.tsx")
};
